package assetmigration

import (
	"fmt"
	"io"
	"strings"
	"time"
)

type SQLUpdateOptions struct {
	Bucket  string
	BatchID string
	Now     func() time.Time
}

func WriteResultSQL(writer io.Writer, results []RowResult, options SQLUpdateOptions) error {
	if writer == nil {
		return fmt.Errorf("writer is required")
	}
	now := options.Now
	if now == nil {
		now = time.Now
	}
	batchID := strings.TrimSpace(options.BatchID)
	if batchID == "" {
		batchID = "asset-migrate-" + now().UTC().Format("20060102T150405Z")
	}
	bucket := strings.TrimSpace(options.Bucket)
	if bucket == "" {
		return fmt.Errorf("bucket is required")
	}
	if _, err := fmt.Fprintln(writer, "-- Generated by cmd/asset-migrate. Review before executing."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(writer, "-- Only rows with action=copied are marked migrated."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(writer, "set session sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO';"); err != nil {
		return err
	}
	wrote := false
	for _, result := range results {
		if result.Action != "copied" {
			continue
		}
		row := result.Row
		logicalKey := strings.TrimSpace(row.LogicalKey)
		storageKey := strings.TrimSpace(row.TargetOSSKey)
		if logicalKey == "" || storageKey == "" {
			continue
		}
		wrote = true
		statement := fmt.Sprintf(`update tb_asset_objects
set storage_provider = 'oss',
    bucket = %s,
    storage_key = %s,
    storage_key_hash = sha2(%s, 256),
    migration_status = 'migrated',
    migration_batch_id = %s,
    migration_attempts = migration_attempts + 1,
    last_attempt_at = current_timestamp(3),
    last_error_code = '',
    last_error_message = '',
    migrated_at = current_timestamp(3)
where logical_key_hash = sha2(%s, 256)
  and migration_status <> 'migrated';`,
			sqlString(bucket),
			sqlString(storageKey),
			sqlString(storageKey),
			sqlString(batchID),
			sqlString(logicalKey),
		)
		if _, err := fmt.Fprintln(writer, statement); err != nil {
			return err
		}
	}
	if !wrote {
		_, err := fmt.Fprintln(writer, "-- No copied rows; no migration status updates generated.")
		return err
	}
	return nil
}

func sqlString(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}
