// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.2
// - protoc             v3.21.12
// source: proto/soyoung/primecrm/sdy.proto

package primecrm

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// SdyServiceClient is the client API for SdyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SdyServiceClient interface {
	GetQuickMedicalBeautyOverview(ctx context.Context, in *QuickMedicalBeautyDashboardRequest, opts ...grpc_go.CallOption) (*QuickMedicalBeautyOverviewResponse, common.ErrorWithAttachment)
	GetQuickMedicalBeautyDutyStaff(ctx context.Context, in *QuickMedicalBeautyDashboardRequest, opts ...grpc_go.CallOption) (*QuickMedicalBeautyDutyStaffResponse, common.ErrorWithAttachment)
	GetQuickMedicalBeautyTrafficFlow(ctx context.Context, in *QuickMedicalBeautyDashboardRequest, opts ...grpc_go.CallOption) (*QuickMedicalBeautyTrafficFlowResponse, common.ErrorWithAttachment)
}

type sdyServiceClient struct {
	cc *triple.TripleConn
}

type SdyServiceClientImpl struct {
	GetQuickMedicalBeautyOverview    func(ctx context.Context, in *QuickMedicalBeautyDashboardRequest) (*QuickMedicalBeautyOverviewResponse, error)
	GetQuickMedicalBeautyDutyStaff   func(ctx context.Context, in *QuickMedicalBeautyDashboardRequest) (*QuickMedicalBeautyDutyStaffResponse, error)
	GetQuickMedicalBeautyTrafficFlow func(ctx context.Context, in *QuickMedicalBeautyDashboardRequest) (*QuickMedicalBeautyTrafficFlowResponse, error)
}

func (c *SdyServiceClientImpl) GetDubboStub(cc *triple.TripleConn) SdyServiceClient {
	return NewSdyServiceClient(cc)
}

func NewSdyServiceClient(cc *triple.TripleConn) SdyServiceClient {
	return &sdyServiceClient{cc}
}

func (c *sdyServiceClient) GetQuickMedicalBeautyOverview(ctx context.Context, in *QuickMedicalBeautyDashboardRequest, opts ...grpc_go.CallOption) (*QuickMedicalBeautyOverviewResponse, common.ErrorWithAttachment) {
	out := new(QuickMedicalBeautyOverviewResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetQuickMedicalBeautyOverview", in, out)
}

func (c *sdyServiceClient) GetQuickMedicalBeautyDutyStaff(ctx context.Context, in *QuickMedicalBeautyDashboardRequest, opts ...grpc_go.CallOption) (*QuickMedicalBeautyDutyStaffResponse, common.ErrorWithAttachment) {
	out := new(QuickMedicalBeautyDutyStaffResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetQuickMedicalBeautyDutyStaff", in, out)
}

func (c *sdyServiceClient) GetQuickMedicalBeautyTrafficFlow(ctx context.Context, in *QuickMedicalBeautyDashboardRequest, opts ...grpc_go.CallOption) (*QuickMedicalBeautyTrafficFlowResponse, common.ErrorWithAttachment) {
	out := new(QuickMedicalBeautyTrafficFlowResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetQuickMedicalBeautyTrafficFlow", in, out)
}

// SdyServiceServer is the server API for SdyService service.
// All implementations must embed UnimplementedSdyServiceServer
// for forward compatibility
type SdyServiceServer interface {
	GetQuickMedicalBeautyOverview(context.Context, *QuickMedicalBeautyDashboardRequest) (*QuickMedicalBeautyOverviewResponse, error)
	GetQuickMedicalBeautyDutyStaff(context.Context, *QuickMedicalBeautyDashboardRequest) (*QuickMedicalBeautyDutyStaffResponse, error)
	GetQuickMedicalBeautyTrafficFlow(context.Context, *QuickMedicalBeautyDashboardRequest) (*QuickMedicalBeautyTrafficFlowResponse, error)
	mustEmbedUnimplementedSdyServiceServer()
}

// UnimplementedSdyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSdyServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedSdyServiceServer) GetQuickMedicalBeautyOverview(context.Context, *QuickMedicalBeautyDashboardRequest) (*QuickMedicalBeautyOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuickMedicalBeautyOverview not implemented")
}
func (UnimplementedSdyServiceServer) GetQuickMedicalBeautyDutyStaff(context.Context, *QuickMedicalBeautyDashboardRequest) (*QuickMedicalBeautyDutyStaffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuickMedicalBeautyDutyStaff not implemented")
}
func (UnimplementedSdyServiceServer) GetQuickMedicalBeautyTrafficFlow(context.Context, *QuickMedicalBeautyDashboardRequest) (*QuickMedicalBeautyTrafficFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuickMedicalBeautyTrafficFlow not implemented")
}
func (s *UnimplementedSdyServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedSdyServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedSdyServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &SdyService_ServiceDesc
}
func (UnimplementedSdyServiceServer) mustEmbedUnimplementedSdyServiceServer() {}

// UnsafeSdyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SdyServiceServer will
// result in compilation errors.
type UnsafeSdyServiceServer interface {
	mustEmbedUnimplementedSdyServiceServer()
}

func RegisterSdyServiceServer(s grpc_go.ServiceRegistrar, srv SdyServiceServer) {
	s.RegisterService(&SdyService_ServiceDesc, srv)
}

func _SdyService_GetQuickMedicalBeautyOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuickMedicalBeautyDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetQuickMedicalBeautyOverview", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.soyoung.primecrm.SdyService/GetQuickMedicalBeautyOverview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdyServiceServer).GetQuickMedicalBeautyOverview(ctx, req.(*QuickMedicalBeautyDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdyService_GetQuickMedicalBeautyDutyStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuickMedicalBeautyDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetQuickMedicalBeautyDutyStaff", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.soyoung.primecrm.SdyService/GetQuickMedicalBeautyDutyStaff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdyServiceServer).GetQuickMedicalBeautyDutyStaff(ctx, req.(*QuickMedicalBeautyDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdyService_GetQuickMedicalBeautyTrafficFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuickMedicalBeautyDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetQuickMedicalBeautyTrafficFlow", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.soyoung.primecrm.SdyService/GetQuickMedicalBeautyTrafficFlow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdyServiceServer).GetQuickMedicalBeautyTrafficFlow(ctx, req.(*QuickMedicalBeautyDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SdyService_ServiceDesc is the grpc_go.ServiceDesc for SdyService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var SdyService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "com.soyoung.primecrm.SdyService",
	HandlerType: (*SdyServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "GetQuickMedicalBeautyOverview",
			Handler:    _SdyService_GetQuickMedicalBeautyOverview_Handler,
		},
		{
			MethodName: "GetQuickMedicalBeautyDutyStaff",
			Handler:    _SdyService_GetQuickMedicalBeautyDutyStaff_Handler,
		},
		{
			MethodName: "GetQuickMedicalBeautyTrafficFlow",
			Handler:    _SdyService_GetQuickMedicalBeautyTrafficFlow_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "proto/soyoung/primecrm/sdy.proto",
}
